name: Java CI Build and Artifact Upload

on:
  push:
    branches: [ main ]

jobs:
  build-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./Board 

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: tictactoe
        path: ./Board/target/tictactoe.jar
