name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn deploy
        working-directory: ./Board

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: tic-tac-toe-jar
          path: target/*.jar
